"""Renamed maximun_number_of_spots to maximum_number_of_spots

Revision ID: d1387a208024
Revises: ac923fdaad15
Create Date: 2025-07-28 20:58:56.548289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1387a208024'
down_revision = 'ac923fdaad15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.alter_column(
            column_name='maximun_number_of_spots',
            new_column_name='maximum_number_of_spots'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.alter_column(
            column_name='maximum_number_of_spots',
            new_column_name='maximun_number_of_spots'
        )
    # ### end Alembic commands ###
